### ISSUE TITLE
[Feature Request] Dismiss notification all devices, 

### ISSUE THREAD

**Issue by Iz-zzzzz** [choiman1559/NotiSender#10]
1. Option to dismiss notification in all devices when dismiss one of those.
2. Additional action in recipient device. For example, Samsung Capture should has "Share", "Edit" and "Delete".

**Comment by choiman1559** [comment]
Partially implemented in version 1.19.7.
(When dismissing a synced notification, it is dismissed only on the device that sent the notification.)
Related commit: https://github.com/choiman1559/NotiSender/commit/d2f5fcc662f05ba60d1ded2f7116b93097babfdc

**Comment by choiman1559** [comment]
Finally, Exactly an year later, These request are fully implemented on version 1.22.1

Related Commits:
1. [Remove mirrored notification when dismissed on origin device](https://github.com/choiman1559/NotiSender/commit/b67b19b7f8b161ec154703da7396d9c81aaff934)
2. [Implemented Reply on mirrored InputAction Notifications](https://github.com/choiman1559/NotiSender/commit/af4f580340e7ea788f34f7453ff0eef5a010eb12)
