### ISSUE TITLE
Not working on Android 14

### ISSUE THREAD

**Issue by incom2** [choiman1559/NotiSender#11]
Hi, after upgrading my Pixel 4a (5G) device, NotiSender is not working anymore. It just doesn't open and ends throwing the usual dialog "this app is not working, etc".

**Comment by choiman1559** [comment]
Google Play billing API-related problem (https://github.com/android/play-billing-samples/issues/618), Fixed in 1.19.7.
Related commit: https://github.com/choiman1559/NotiSender/commit/310ae98b84f6c4083b05a20b9f6729c0e79f992c
