### ISSUE TITLE
Service on\off

### ISSUE THREAD

**Issue by fcaronte** [choiman1559/NotiSender#12]
I Discovery this app today and I would to understand if I can turn on\off the service when Connected to car Bluetooth only and keep off when I'm not in the car, I can't find this setting if exist

**Comment by choiman1559** [comment]
Try it in combination with an Android automation application called Tasker.

1) NotiSender Home -> Plugin & User scripts -> Enable Tasker Plugin toggle On

2) Install Tasker (or a compatible application).
Compatible automation applications: Tasker, Automate, Locale X, MacroDroid

3) Follow the instructions in Tasker to create an event upon Bluetooth connection.

4) In the Tasker action, select Plugin -> Noti Sender and select the desired action in Configuration.
