### ISSUE TITLE
Can't enable telephony plugin 

### ISSUE THREAD

**Issue by fcaronte** [choiman1559/NotiSender#13]
I don't know if I'm doing something wrong but seem I can't enable phone plugin it switch off itself when exit from menù. I install the plugin and give all permissions
This is a video example
https://github.com/choiman1559/NotiSender/assets/26366403/d48647ed-2c27-48f9-b7be-5e5b9b641e32

Ps automate plugin work correctly thanks 👍🏻

**Comment by choiman1559** [comment]
Bug resolved.
Scheduled to be distributed in release 1.20.7

Problem: An issue where plugins that do not use Sensitive API are not activated
Related Commit: https://github.com/choiman1559/NotiSender/commit/7088c71db2170fbb512300241cc5b99a84096083

**Comment by fcaronte** [comment]
> Bug resolved.
> Scheduled to be distributed in release 1.20.7
> 
> Problem: An issue where plugins that do not use Sensitive API are not activated
> Related Commit: https://github.com/choiman1559/NotiSender/commit/7088c71db2170fbb512300241cc5b99a84096083

I have a question, is this app need Bluetooth connection phone to phone? Because I want to use old phone in the car for android auto connecting and I must force Bluetooth disabled using root to be able to keep main phone connected to car Bluetooth system, and I see today's that app crash when try to send a notification or o try to manage the second phone
