### ISSUE TITLE
can't get live notifications update

### ISSUE THREAD

**Issue by eliascore** [choiman1559/NotiSender#16]
I can't get live notifications update, even when i tried to refresh the tab repeatedly. please help
![Screenshot_20241006_052212_Noti Sender](https://github.com/user-attachments/assets/8ec2189f-f6dc-4773-8f8b-ede2fb67549e)

**Comment by choiman1559** [comment]
It seems like it's probably a data expiration issue on the server.

Can you tell me your email address so I can check the server-side log?
The server identifies users by anonymous UID, so I can't track the error if I don't know your email address.

Additionally, try changing the server channel to Test Server in "Other Options" and see if the same issue occurs.

**Comment by eliascore** [comment]
Thank you so much for your attention.
my email address is : **Removed**
anyway, I've tried using test servers but it returned with same error.
also, I've tried to uninstall, then reinstall the apps both via google play and github, but the problem persist.
is it possible that the problem is in the sender device?

**Comment by choiman1559** [comment]
When I checked the server log, there was no record of receiving data from the Sender device, so it seems to be a problem with the Sender device.

Could you please check if the Sender device has the permission to read notifications properly? (The "Skip Alarm access permission for now" checkbox should not have been set when the app was initially set up.)

If not, could you try again after manually clearing all notifications on the Sender device?
In this case, the "No Notifications" message should be successfully displayed on the Receiver device.

**Comment by eliascore** [comment]
thanks for your attention. since the sender device isn't in my hand right now, I'll try to check it later
