### ISSUE TITLE
How to connect 2 android devices using different google accounts?

### ISSUE THREAD

**Issue by voxvargr** [choiman1559/NotiSender#18]
I'm trying to figure this out but I'm lost currently

I have 2 phones, work and personal. I'd like to see notifications from the work phone without carrying it 24/7 so is it possible to use this to send notifications from it to my personal device?

I don't want my work account on my personal device nor my personal account on my work device but I can't find a way to pair them without that being the case. Is there a way to just use the unique address the app gives my phone to pair them instead?

**Comment by choiman1559** [comment]
No, this is technically possible, but for security reasons, it is not allowed.

NotiSender uses a unique Pre-Shared Key (PSK) for each user (or group of devices) to separate traffic between users, allowing only devices registered with the server to communicate.
(The key used at this time is also called a Topic or Group key.)

In the case of NotiSender, a UID issued by a third-party OAuth server such as Google is used as the PSK for security,
but there is generally no restriction on the format of the PSK, and in the case of a military variation of NotiSender, such as [SyncTAK](https://github.com/choiman1559/SyncTAK), it allows the user to directly enter the PSK without a separate login process.

However, requiring the user to directly enter the PSK poses potential security risks, such as key leakage or accidentally using a duplicate key with another user, which can lead to third-party exposure of data and packet injection attacks.

Therefore, in the general user's usage pattern, it is not only unnecessary to use it, but also dangerous, so it is not allowed.
However, in special use cases such as the military purpose mentioned above, corporate use, or headless embedded devices, this feature can still be useful,
so we are implementing and providing customized clients through separate contracts.

If you need a enterprise license contract, please contact cuj1559@gmail.com.
We are willing to provide customized services such as improved E2E encryption, On-Premise Backend, MDM, etc. to our customers.
