### ISSUE TITLE
Reply by notification

### ISSUE THREAD

**Issue by Haf0** [choiman1559/NotiSender#5]
is there a way to reply chat or something using recipient device?

**Comment by choiman1559** [comment]
Well. It supports replies to native phone call and SMS apps, but not to third-party apps like Whatsapp or Telegram.

I could consider adding a feature, but it will take some time as I'm currently focused on developing a client for PC.

**Comment by choiman1559** [comment]
Implemented on version 1.22.1.
Related commit: [Implemented Reply on mirrored InputAction Notifications](https://github.com/choiman1559/NotiSender/commit/af4f580340e7ea788f34f7453ff0eef5a010eb12)
